<#
MailPolicyExplainer.psd1 -- manifest file for said module
Copyright (C) 2018, 2020, 2023-2025 Colin Cogle.  All Rights Reserved.

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <https://www.gnu.org/licenses/>.
#>

# Module manifest for module 'MailPolicyExplainer'
# Generated by: Colin Cogle
# Generated on: 4/18/2018
@{

# Script module or binary module file associated with this manifest.
RootModule = 'src/MailPolicyExplainer.psm1'

# Version number of this module.
ModuleVersion = '1.5.0'

# Supported PSEditions
CompatiblePSEditions = @('Core', 'Desktop')

# ID used to uniquely identify this module
GUID = 'b3ec0108-05d3-43f1-a5ba-cc8f7f4cc8cc'

# Author of this module
Author = 'Colin Cogle'

# Copyright statement for this module
Copyright = '(c) 2018, 2020, 2023-2025 Colin Cogle. All rights reserved.'

# Description of the functionality provided by this module
Description = "Explains a domain's email DNS records, including MX, SPF, DKIM, DMARC, and more."

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Things to export from this module, for best performance, do not use wildcards
# and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport   = ''
VariablesToExport = ''
FunctionsToExport = @(
	'Test-MailPolicy',
	'Test-MXRecord',
	'Test-IPVersions',
	'Test-DkimSelector',
	'Test-AdspRecord',
	'Test-DmarcRecord',
	'Test-BimiSelector',
	'Test-MtaStsPolicy',
	'Test-SmtpTlsReportingPolicy',
	'Test-SpfRecord',
	'Test-DaneRecord',
	'Invoke-GooglePublicDnsApi'
)
AliasesToExport = @(
	'Test-BimiRecord',
	'Test-DaneRecords',
	'Test-DkimRecord',
	'Test-DomainKeysRecord',
	'Test-DomainKeysSelector',
	'Test-MtaStsRecord',
	'Test-MXRecords',
	'Test-NullMXRecord',
	'Test-SenderIdRecord',
	'Test-TlsaRecord',
	'Test-TlsaRecords'
)

# List of all files packaged with this module
FileList = @(
	'en-US/about_BIMI.help.txt',
	'en-US/about_DANERecords.help.txt',
	'en-US/about_DANERecordsAcronyms.help.txt',
	'en-US/about_DANERecordsUsage.help.txt',
	'en-US/about_DKIM.help.txt',
	'en-US/about_DKIMADSP.help.txt',
	'en-US/about_DKIMEd25519.help.txt',
	'en-US/about_DKIMRSAKeyUpdates.help.txt',
	'en-US/about_DMARC.help.txt',
	'en-US/about_IDNEmailAuthentication.help.txt',
	'en-US/about_MailPolicyExplainer.help.txt',
	'en-US/about_MTA-STS.help.txt',
	'en-US/about_MXRecords.help.txt',
	'en-US/about_NullMXRecords.help.txt',
	'en-US/about_SMTP.help.txt',
	'en-US/about_SMTPTLSReporting.help.txt',
	'en-US/about_SPF.help.txt',
	'src/MailPolicyExplainer.psm1',
	'AUTHORS.txt',
	'CHANGELOG.md',
	'CODE_OF_CONDUCT.md',
	'CONTRIBUTING.md',
	'INSTALL.md',
	'LICENSE.md',
	'MailPolicyExplainer.psd1',
	'NEWS.md',
	'ONEWS.md',
	'README.md',
	'SECURITY.md',
	'THANKS.md'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess.
# This may also contain a PSData hashtable with additional module metadata used
# by PowerShell.
PrivateData = @{
	PSData = @{
		#Prerelease = 'git'

		# Tags applied to this module.
		# These help with module discovery in online galleries.
		Tags = @(
			'email', 'mail', 'SPF', 'DKIM', 'DMARC', 'BIMI', 'DNSSEC', 'DANE',
			'MTA-STS', 'MX', 'TLSRPT', 'STARTTLS', 'domainkey', 'TLS', 'TLSA',
			'ADSP',  'DNS', 'policy', 'SenderID', 'tester', 'Reporting', 'Test',
			'Exchange', 'ExchangeOnline', 'ExO', 'Microsoft365', 'Office365',
			'Google', 'Network', 'Cloud', 'security', 'teaching', 'ELI5',
			'audit', 'IPv4', 'IPv6', 'SMTP', 'RSA', 'Ed25519', 'DomainKeys',
			'Windows', 'MacOS', 'Linux', 'PSEdition_Core', 'PSEdition_Desktop'
		)

		LicenseUri = 'https://github.com/rhymeswithmogul/MailPolicyExplainer/blob/main/LICENSE.txt'
		ProjectUri = 'https://github.com/rhymeswithmogul/MailPolicyExplainer'
		IconUri = 'https://raw.githubusercontent.com/rhymeswithmogul/MailPolicyExplainer/main/icon/PSGallery.png'

		ReleaseNotes = '- Add the `Test-MailPolicy -ExchangeOnline` parameter for quick testing of selector1 and selector2.
- Fix several bugs related to Sender ID checks.
- Generic module cleanup.'
	}
}

}
